# =============================================================================
# GitLab CI/CD Pipeline - MS-USERS
# Construye y sube imagen Docker optimizada para 250 MiB
# =============================================================================

stages:
     - build
     - docker-build

variables:
     DOCKER_IMAGE_NAME: "isaelfatamadev/jass-ms-users"
     DOCKER_TAG: "250mib"
     MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

# Cache para optimizar builds
cache:
     paths:
          - .m2/repository/
          - target/

# =============================================================================
# STAGE 1: Build & Test
# =============================================================================
maven-build:
     stage: build
     image: maven:3.9.6-eclipse-temurin-17-alpine
     script:
          - echo "🚀 Iniciando build del MS-Users..."
          - mvn --version
          - java -version
          - echo "📦 Descargando dependencias..."
          - mvn dependency:resolve -B -q
          - echo "🔨 Compilando proyecto..."
          - mvn clean compile -B -q
          - echo "🧪 Ejecutando tests..."
          - mvn test -B
          - echo "📋 Generando JAR..."
          - mvn package -DskipTests -B -q
          - ls -la target/
     artifacts:
          paths:
               - target/*.jar
          expire_in: 1 hour
     only:
          - main
          - develop
          - merge_requests

# =============================================================================
# STAGE 2: Docker Build & Push
# =============================================================================
docker-build-push:
     stage: docker-build
     image: docker:24.0.5
     services:
          - docker:24.0.5-dind
     variables:
          DOCKER_DRIVER: overlay2
          DOCKER_TLS_CERTDIR: "/certs"
     before_script:
          - echo "🐳 Configurando Docker..."
          - docker info
          - echo "🔑 Autenticando con DockerHub..."
          - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
     script:
          - echo "🏗️ Construyendo imagen Docker optimizada para 250 MiB..."
          - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG .
          - docker build -t $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
          - echo "📤 Subiendo imagen a DockerHub..."
          - docker push $DOCKER_IMAGE_NAME:$DOCKER_TAG
          - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
          - echo "✅ Imagen subida exitosamente:"
          - echo "   - $DOCKER_IMAGE_NAME:$DOCKER_TAG"
          - echo "   - $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
     after_script:
          - docker logout
     dependencies:
          - maven-build
     only:
          - main
          - develop
# =============================================================================
# ✅ Pipeline completo hasta subir imagen optimizada a DockerHub
# =============================================================================
# =============================================================================
# Variables de entorno requeridas en GitLab:
# DOCKERHUB_USERNAME: isaelfatamadev
# DOCKERHUB_TOKEN: dckr_pat_38VCJepK1-a8K0AdJOwSRfmFq2Y
# =============================================================================
